### PR TITLE
oneapi 2024.2 release

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by rscohn2** [comment]
@eugeneswalker

**Comment by eugeneswalker** [comment]
Thanks! I pushed a commit here to add MPI and MKL:
* https://github.com/UO-OACISS/e4s/pull/5/commits/7eba7ca65557f9fcfb14c9e4471d4dda095549f5

Do you see any issue with this? If not, we will merge.

**Comment by rscohn2** [comment]
> Do you see any issue with this? If not, we will merge.

I don't see any issue, but I was assuming that it is not needed because spack will install mpi/mkl if a package depends on it.

**Comment by eugeneswalker** [comment]
> > Do you see any issue with this? If not, we will merge.
> 
> I don't see any issue, but I was assuming that it is not needed because spack will install mpi/mkl if a package depends on it.

Yes, let us include them here so that we can use this same container also for testing Spack installs against the externally provided MPI/MKL.

**Pull request merged**
